# SPDX-License-Identifier: AGPL-3.0-or-later
<#
.SYNOPSIS
  Builds launcher\bin\CrownAndCardLauncher.exe.

.DESCRIPTION
  1. Compiles the menu-music decoder (native\cc_vorbis.c, a wrapper around
     stb_vorbis) into a 64-bit DLL with MSVC.
  2. Compiles the launcher with the C# compiler, targeting .NET Framework 4.8,
     which ships with Windows 10 and 11. The decoder DLL and the menu loop
     (res\audio\music\menu-loop-dark.ogg) are embedded, so the exe is a single
     file with nothing to install.

  Needs Visual Studio Build Tools with the C# and C++ (MSVC) workloads.

  -Package also assembles dist\CrownAndCard\ (the launcher plus the web build;
  run `haxe build-js.hxml` first) and zips it as
  dist\CrownAndCard-<version>-win64.zip with a .sha256 file: the GitHub
  release asset the launcher's updater installs (see tools\release.ps1).
#>
param([switch]$Package)
$ErrorActionPreference = "Stop"

$root = $PSScriptRoot
$vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { throw "Visual Studio Build Tools weren't found (no vswhere.exe)." }
$csc = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\Roslyn\csc.exe" | Select-Object -First 1
if (-not $csc) { throw "The C# compiler (Roslyn csc.exe) wasn't found. Install Visual Studio Build Tools with the .NET desktop build tools." }
$vcvars = & $vswhere -latest -products * -find "VC\Auxiliary\Build\vcvars64.bat" | Select-Object -First 1
if (-not $vcvars) { throw "MSVC (vcvars64.bat) wasn't found. Install Visual Studio Build Tools with the C++ build tools." }

$framework = Join-Path $env:WINDIR "Microsoft.NET\Framework64\v4.0.30319"
$references = "mscorlib.dll", "System.dll", "System.Core.dll", "System.Drawing.dll", "System.Windows.Forms.dll",
    "System.Net.Http.dll", "System.Web.Extensions.dll", "System.Xml.dll", "System.Xml.Linq.dll", "System.Management.dll",
    "System.IO.Compression.dll", "System.IO.Compression.FileSystem.dll" |
    ForEach-Object { "/reference:" + (Join-Path $framework $_) }

# Version: 0.YY.BBB from version.json (bump with `python tools\version.py bump`).
$repo = Split-Path $root -Parent
$version = (Get-Content (Join-Path $repo "version.json") -Raw | ConvertFrom-Json).version
if ($version -notmatch '^(\d+)\.(\d+)\.(\d+)$') { throw "version.json has '$version'; expected 0.YY.BBB." }
$numeric = "{0}.{1}.{2}.0" -f [int]$Matches[1], [int]$Matches[2], [int]$Matches[3]

# Build from the launcher folder with relative paths: the repo path may contain
# spaces, which Windows PowerShell quotes in a way csc's /win32icon: parsing rejects.
Push-Location $root
try {
    New-Item -ItemType Directory -Force "bin\native" | Out-Null

    # 1. Native decoder. A generated .cmd runs vcvars64 and cl in one cmd session,
    #    which avoids PowerShell's quoting of paths with spaces.
    $music = "..\res\audio\music\menu-loop-dark.ogg"
    if (-not (Test-Path $music)) { throw "Missing $music (the menu loop)." }
    @(
        "@echo off",
        "set `"PATH=$(Split-Path $vswhere);%PATH%`"",
        "call `"$vcvars`" >nul 2>&1 || exit /b 1",
        "cl /nologo /O2 /LD /MT /W3 /wd4244 /wd4245 /wd4456 /wd4457 /wd4701 /wd4996 /DNDEBUG native\cc_vorbis.c /Fobin\native\ /Febin\native\cc_vorbis.dll /link /NOLOGO 2>&1"
    ) | Set-Content -Encoding ASCII "bin\native\build-native.cmd"
    # Windows PowerShell treats any stderr text from a native tool as an error; judge by exit code instead.
    $ErrorActionPreference = "Continue"
    & cmd /c "bin\native\build-native.cmd" | Out-Host
    $ErrorActionPreference = "Stop"
    if ($LASTEXITCODE -ne 0) { throw "Native decoder build failed." }

    # 2. Launcher, with the version baked in.
    New-Item -ItemType Directory -Force "bin\generated" | Out-Null
    @(
        "// Generated by build.ps1 from version.json. Don't edit.",
        "[assembly: System.Reflection.AssemblyVersion(`"$numeric`")]",
        "[assembly: System.Reflection.AssemblyFileVersion(`"$numeric`")]",
        "[assembly: System.Reflection.AssemblyInformationalVersion(`"$version`")]",
        "namespace CrownAndCard.Launcher;",
        "static class BuildInfo { public const string Version = `"$version`"; }"
    ) | Set-Content -Encoding UTF8 "bin\generated\BuildInfo.cs"
    $sources = @(Get-ChildItem "src" -Recurse -Filter *.cs | ForEach-Object { Resolve-Path -Relative $_.FullName }) + "bin\generated\BuildInfo.cs"
    $arguments = @(
        "/nologo", "/noconfig", "/nostdlib+", "/target:winexe", "/platform:x64", "/optimize+",
        "/langversion:latest", "/nullable:enable", "/warn:4",
        "/out:bin\CrownAndCardLauncher.exe",
        "/win32icon:assets\launcher.ico",
        "/win32manifest:app.manifest",
        "/resource:bin\native\cc_vorbis.dll,CrownAndCard.Launcher.cc_vorbis.dll",
        "/resource:$music,CrownAndCard.Launcher.menu-loop-dark.ogg"
    ) + $references + $sources
    & $csc @arguments
    if ($LASTEXITCODE -ne 0) { throw "Compile failed." }
}
finally {
    Pop-Location
}
$exe = Join-Path $root "bin\CrownAndCardLauncher.exe"
Write-Host "Built $exe ($version)"

if ($Package) {
    $web = Join-Path $repo "web"
    if (-not (Test-Path (Join-Path $web "game.js"))) { throw "web\game.js is missing; run 'haxe build-js.hxml' first." }
    $dist = Join-Path $repo "dist\CrownAndCard"
    if (Test-Path $dist) { Remove-Item -Recurse -Force $dist }
    New-Item -ItemType Directory -Force (Join-Path $dist "web") | Out-Null
    Copy-Item $exe $dist
    Copy-Item (Join-Path $web "index.html"), (Join-Path $web "game.js") (Join-Path $dist "web")
    Copy-Item (Join-Path $repo "LICENSE"), (Join-Path $repo "LICENSE-ASSETS"), (Join-Path $repo "version.json") $dist
    Write-Host "Packaged $dist"

    # The GitHub release asset the launcher's updater looks for, plus its SHA-256.
    $zip = Join-Path $repo "dist\CrownAndCard-$version-win64.zip"
    if (Test-Path $zip) { Remove-Item -Force $zip }
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::CreateFromDirectory($dist, $zip, [System.IO.Compression.CompressionLevel]::Optimal, $false)
    $hash = (Get-FileHash -Algorithm SHA256 $zip).Hash.ToLowerInvariant()
    "$hash  $(Split-Path $zip -Leaf)" | Set-Content -Encoding ASCII "$zip.sha256"
    Write-Host "Release zip: $zip"
    Write-Host "SHA-256:     $hash"
}
