# SPDX-License-Identifier: AGPL-3.0-or-later
<#
.SYNOPSIS
  Builds launcher\bin\CrownAndCardLauncher.exe (and, with -Package, the release).

.DESCRIPTION
  1. Compiles the menu-music decoder (native\cc_vorbis.c, a wrapper around
     stb_vorbis) into a 64-bit cc_vorbis.dll with MSVC, using Visual Studio's
     own DevShell for the compiler environment.
  2. Compiles the launcher with the C# compiler, targeting .NET Framework 4.8,
     which ships with Windows 10 and 11.

  The DLL and the menu loop ship as ordinary files next to the exe
  (cc_vorbis.dll, music\menu-loop-dark.ogg). Nothing is embedded and unpacked
  at run time: behavior-based antivirus treats that pattern as malware.

  -Package also assembles dist\CrownAndCard\ (the launcher, the web build,
  the music and the licenses; run `haxe build-js.hxml` first), zips it as
  dist\CrownAndCard-<version>-win64.zip (+ .sha256), and builds the installer
  dist\CrownAndCard-Setup-<version>.exe with Inno Setup (installer\CrownAndCard.iss).

  Needs Visual Studio Build Tools (C# and C++ workloads); -Package also needs
  Inno Setup 6 (winget install JRSoftware.InnoSetup).
#>
param([switch]$Package)
$ErrorActionPreference = "Stop"

$root = $PSScriptRoot
$repo = Split-Path $root -Parent
$vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { throw "Visual Studio Build Tools weren't found (no vswhere.exe)." }
$vsPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath | Select-Object -First 1
if (-not $vsPath) { throw "MSVC wasn't found. Install Visual Studio Build Tools with the C++ build tools." }
$csc = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\Roslyn\csc.exe" | Select-Object -First 1
if (-not $csc) { throw "The C# compiler (Roslyn csc.exe) wasn't found. Install Visual Studio Build Tools with the .NET desktop build tools." }

$framework = Join-Path $env:WINDIR "Microsoft.NET\Framework64\v4.0.30319"
$references = "mscorlib.dll", "System.dll", "System.Core.dll", "System.Drawing.dll", "System.Windows.Forms.dll",
    "System.Net.Http.dll", "System.Web.Extensions.dll", "System.Xml.dll", "System.Xml.Linq.dll" |
    ForEach-Object { "/reference:" + (Join-Path $framework $_) }

# Version: 0.YY.BBB from version.json (bump with `python tools\version.py bump`).
$version = (Get-Content (Join-Path $repo "version.json") -Raw | ConvertFrom-Json).version
if ($version -notmatch '^(\d+)\.(\d+)\.(\d+)$') { throw "version.json has '$version'; expected 0.YY.BBB." }
$numeric = "{0}.{1}.{2}.0" -f [int]$Matches[1], [int]$Matches[2], [int]$Matches[3]

# Build from the launcher folder with relative paths: the repo path may contain
# spaces, which Windows PowerShell quotes in a way csc's /win32icon: parsing rejects.
Push-Location $root
try {
    New-Item -ItemType Directory -Force "bin\native", "bin\generated" | Out-Null

    # 1. Native decoder, in a child PowerShell so the compiler environment doesn't leak into this one.
    $native = @"
`$ErrorActionPreference = 'Stop'
`$env:PATH = '$(Split-Path $vswhere);' + `$env:PATH
Import-Module '$vsPath\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
Enter-VsDevShell -VsInstallPath '$vsPath' -SkipAutomaticLocation -DevCmdArguments '-arch=x64 -host_arch=x64 -no_logo' | Out-Null
Set-Location '$root'
cl /nologo /O2 /LD /MT /W3 /wd4244 /wd4245 /wd4456 /wd4457 /wd4701 /wd4996 /DNDEBUG native\cc_vorbis.c /Fobin\native\ /Febin\native\cc_vorbis.dll /link /NOLOGO
exit `$LASTEXITCODE
"@
    # Windows PowerShell treats any stderr text from a native tool as an error; judge by exit code instead.
    $ErrorActionPreference = "Continue"
    & powershell -NoProfile -ExecutionPolicy Bypass -Command $native 2>&1 | Out-Host
    $ErrorActionPreference = "Stop"
    if ($LASTEXITCODE -ne 0) { throw "Native decoder build failed." }
    Copy-Item "bin\native\cc_vorbis.dll" "bin\cc_vorbis.dll" -Force

    # 2. Launcher, with the version baked in.
    @(
        "// Generated by build.ps1 from version.json. Don't edit.",
        "[assembly: System.Reflection.AssemblyVersion(`"$numeric`")]",
        "[assembly: System.Reflection.AssemblyFileVersion(`"$numeric`")]",
        "[assembly: System.Reflection.AssemblyInformationalVersion(`"$version`")]",
        "namespace CrownAndCard.Launcher;",
        "static class BuildInfo { public const string Version = `"$version`"; }"
    ) | Set-Content -Encoding UTF8 "bin\generated\BuildInfo.cs"
    $sources = @(Get-ChildItem "src" -Recurse -Filter *.cs | ForEach-Object { Resolve-Path -Relative $_.FullName }) + "bin\generated\BuildInfo.cs"
    $arguments = @(
        "/nologo", "/noconfig", "/nostdlib+", "/target:winexe", "/platform:x64", "/optimize+",
        "/langversion:latest", "/nullable:enable", "/warn:4",
        "/out:bin\CrownAndCardLauncher.exe",
        "/win32icon:assets\launcher.ico",
        "/win32manifest:app.manifest"
    ) + $references + $sources
    & $csc @arguments
    if ($LASTEXITCODE -ne 0) { throw "Compile failed." }
}
finally {
    Pop-Location
}
$exe = Join-Path $root "bin\CrownAndCardLauncher.exe"
Write-Host "Built $exe ($version)"

if ($Package) {
    $web = Join-Path $repo "web"
    if (-not (Test-Path (Join-Path $web "game.js"))) { throw "web\game.js is missing; run 'haxe build-js.hxml' first." }
    $dist = Join-Path $repo "dist\CrownAndCard"
    if (Test-Path $dist) { Remove-Item -Recurse -Force $dist }
    New-Item -ItemType Directory -Force (Join-Path $dist "web"), (Join-Path $dist "music") | Out-Null
    Copy-Item $exe, (Join-Path $root "bin\cc_vorbis.dll") $dist
    Copy-Item (Join-Path $web "index.html"), (Join-Path $web "game.js") (Join-Path $dist "web")
    Copy-Item (Join-Path $repo "res\audio\music\menu-loop-dark.ogg") (Join-Path $dist "music")
    Copy-Item (Join-Path $repo "LICENSE"), (Join-Path $repo "LICENSE-ASSETS"), (Join-Path $repo "version.json") $dist
    Write-Host "Packaged $dist"

    # Portable zip (for players who'd rather not install), plus its SHA-256.
    $zip = Join-Path $repo "dist\CrownAndCard-$version-win64.zip"
    if (Test-Path $zip) { Remove-Item -Force $zip }
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::CreateFromDirectory($dist, $zip, [System.IO.Compression.CompressionLevel]::Optimal, $false)
    $hash = (Get-FileHash -Algorithm SHA256 $zip).Hash.ToLowerInvariant()
    "$hash  $(Split-Path $zip -Leaf)" | Set-Content -Encoding ASCII "$zip.sha256"
    Write-Host "Portable zip: $zip"

    # Installer (Inno Setup). The launcher's updater downloads and runs this.
    $iscc = @("$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe", "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe", "$env:ProgramFiles\Inno Setup 6\ISCC.exe") |
        Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $iscc) { throw "Inno Setup 6 wasn't found (winget install JRSoftware.InnoSetup)." }
    & $iscc /Q "/DAppVersion=$version" "/DNumericVersion=$numeric" (Join-Path $repo "installer\CrownAndCard.iss")
    if ($LASTEXITCODE -ne 0) { throw "Installer build failed." }
    $setup = Join-Path $repo "dist\CrownAndCard-Setup-$version.exe"
    Write-Host "Installer:    $setup"
    Write-Host "SHA-256:      $((Get-FileHash -Algorithm SHA256 $setup).Hash.ToLowerInvariant())"
}
